### Buscar todos os alunos
GET http://localhost:8080/api/v1/alunos

##################################################################################
### Inserir um aluno
POST http://localhost:8080/api/v1/alunos
Content-Type: application/json

{
    "nome":"Teste do Will"
}

##################################################################################
### Alterar um aluno
PUT http://localhost:8080/api/v1/alunos/54936471-6c82-41cc-9d1d-1a6b3ab588cb
Content-Type: application/json

{

    "nome":"Willian"
}

##################################################################################
### Deletar um aluno
DELETE http://localhost:8080/api/v1/alunos/54936471-6c82-41cc-9d1d-1a6b3ab588cb
